version: '3'
services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    network_mode: "bridge"
    container_name: destalinator
    image: devedmonton/destalinator
    ports:
      - "8000"
    volumes:
      - .:/usr/src/app
    command: /bin/bash
    tty: true
    stdin_open: true

